export const AUTH_FORM = 'AUTH/FORM_FILLING'
export const REGISTER = 'AUTH/REGISTER'
export const LOGIN = 'AUTH/LOGIN'
export const AUTH_FORM_SWITCH = 'AUTH/FORM_SWITCH'
export const AUTH_DATA = 'AUTH/DATA'
export const NEWS_LIST = 'NEWS/LIST'
export const NEWS_DELETE = 'NEWS/DELETE'
export const NEWS_APPROVED = 'NEWS/APPROVED'
